/* ログイン */
\connect - pgtest;
\c pgtest;

/* SCHEMAを作成 */
CREATE SCHEMA IF NOT EXISTS pgtest AUTHORIZATION pgtest;

/* ドメインを作成します。 */
CREATE DOMAIN pgtest.DOMAIN_VERSION AS INT;
CREATE DOMAIN pgtest.DOMAIN_DELETE_FLAG AS BOOLEAN;
CREATE DOMAIN pgtest.DOMAIN_CREATE_DATETIME AS TIMESTAMP;
CREATE DOMAIN pgtest.DOMAIN_UPDATE_DATETIME AS TIMESTAMP;

/* TABLEを作成 */
CREATE TABLE IF NOT EXISTS pgtest.SAMPLE (
    ID SERIAL NOT NULL,
    SAMPLE_NAME VARCHAR(256),
    VERSION DOMAIN_VERSION,
    DELETE_FLAG DOMAIN_DELETE_FLAG,
    CREATE_DATETIME DOMAIN_CREATE_DATETIME,
    UPDATE_DATETIME DOMAIN_UPDATE_DATETIME,
    PRIMARY KEY (id)
)